CREATE OR REPLACE TRIGGER GROUPS_LOGGER
AFTER INSERT OR UPDATE OR DELETE ON GROUPS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO GROUPS_AUDIT (GROUP_ID, GROUP_NAME, ACTION_TYPE, ACTION_DATE)
        VALUES (:NEW.ID, :NEW.NAME, 'INSERT', SYSTIMESTAMP);
    ELSIF UPDATING THEN
        INSERT INTO GROUPS_AUDIT (GROUP_ID, GROUP_NAME, ACTION_TYPE, OLD_GROUP_NAME, ACTION_DATE)
        VALUES (:NEW.ID, :NEW.NAME, 'UPDATE', :OLD.NAME, SYSTIMESTAMP);
    ELSIF DELETING THEN
        INSERT INTO GROUPS_AUDIT (GROUP_ID, GROUP_NAME, ACTION_TYPE, ACTION_DATE)
        VALUES (:OLD.ID, :OLD.NAME, 'DELETE', SYSTIMESTAMP);
    END IF;
END;