INSERT INTO "GROUPS" (ID, NAME, C_VAL)
VALUES (999, 'TEST_STUDENT', 999);

INSERT INTO STUDENTS (ID, NAME, GROUP_ID)
VALUES (999, 'TEST_STUDENT', 999);

DELETE FROM "GROUPS" WHERE ID = 999;

SELECT * FROM STUDENTS WHERE ID = 999;