delete from students;
delete from "GROUPS";

SELECT * FROM "GROUPS";
SELECT * FROM STUDENTS;

INSERT INTO GROUPS (ID, NAME, C_VAL) VALUES (101, 'Group A', 0);
INSERT INTO GROUPS (ID, NAME, C_VAL) VALUES (102, 'Group B', 0);
INSERT INTO GROUPS (ID, NAME, C_VAL) VALUES (103, 'Group C', 0);

INSERT INTO STUDENTS (ID, NAME, GROUP_ID) VALUES (student_id_seq.NEXTVAL, 'Alice', 101);
INSERT INTO STUDENTS (ID, NAME, GROUP_ID) VALUES (student_id_seq.NEXTVAL, 'Bob', 102);
INSERT INTO STUDENTS (ID, NAME, GROUP_ID) VALUES (student_id_seq.NEXTVAL, 'Charlie', 103);


SELECT * FROM "GROUPS";
SELECT * FROM STUDENTS;

UPDATE STUDENTS SET NAME = 'Alice Updated', GROUP_ID = 101 WHERE NAME = 'Alice';
UPDATE STUDENTS SET NAME = 'Bob', GROUP_ID = 101 WHERE NAME = 'Bob';

SELECT * FROM "GROUPS";
SELECT * FROM STUDENTS;

DELETE FROM GROUPS WHERE ID = 103;

SELECT * FROM "GROUPS";
SELECT * FROM STUDENTS;

EXEC ROLLBACK_IN_SECONDS(60);

SELECT * FROM "GROUPS";
SELECT * FROM STUDENTS;