DELETE FROM "GROUPS" WHERE ID <> 1 AND ID <> 2 AND ID <> 3;

INSERT INTO "GROUPS" (ID, NAME, C_VAL) VALUES (201, 'Group OA', 0);
INSERT INTO "GROUPS" (ID, NAME, C_VAL) VALUES (202, 'Group OAOAO', 0);
INSERT INTO "GROUPS" (ID, NAME, C_VAL) VALUES (203, 'Group OAOAOAO MMMM', 0);

INSERT INTO STUDENTS (ID, NAME, GROUP_ID) VALUES (student_id_seq.NEXTVAL, 'John', 201);
INSERT INTO STUDENTS (ID, NAME, GROUP_ID) VALUES (student_id_seq.NEXTVAL, 'Emily', 202);
INSERT INTO STUDENTS (ID, NAME, GROUP_ID) VALUES (student_id_seq.NEXTVAL, 'David', 203);

SELECT * FROM STUDENTS;

SELECT * FROM "GROUPS";

UPDATE STUDENTS SET GROUP_ID = 202 WHERE NAME = 'John';

SELECT * FROM STUDENTS;

SELECT * FROM "GROUPS";

DELETE FROM STUDENTS WHERE NAME = 'Emily';

SELECT * FROM STUDENTS;

SELECT * FROM "GROUPS";